StudyProjects/Game_MVC_task14/Controllers/CommentController.cs
using System;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Game_MVC.Services.Interfaces;
using Game_MVC_task14.Hubs;
using Microsoft.AspNet.SignalR;

namespace Game_MVC_task14.Controllers
{
    [RoutePrefix("api/Comment")]
    [System.Web.Http.Authorize]
    public class CommentController : ApiController
    {
        private readonly ICommentService commentService;
        private readonly IHubContext notificationHubContext;

        public CommentController(ICommentService commentService)
        {
            this.commentService = commentService;
            this.notificationHubContext = GlobalHost.ConnectionManager.GetHubContext<CommentNotificationHub>();
        }

        [HttpGet]
        public IHttpActionResult GetAll()
        {
            var operationResult = this.commentService.Get();
            if (operationResult.State.IsFail())
            {
                switch (operationResult.Code)
                {
                    case ErrorCode.NotFound:
                        return this.NotFound();
                    case ErrorCode.Other:
                        return this.InternalServerError();
                }
            }

            return this.Json(operationResult.Result);
        }

        [HttpGet]
        [Route("{id}")]
        public IHttpActionResult Get(Guid id)
        {
            var operationResult = this.commentService.GetFirst(item => item.Id == id);
            if (operationResult.State.IsFail())
            {
                switch (operationResult.Code)
                {
                    case ErrorCode.NotFound:
                        return this.NotFound();
                    case ErrorCode.Other:
                        return this.InternalServerError();
                }
            }

            return this.Json(operationResult.Result);
        }

        [HttpPut]
        [Route("{message}")]
        public HttpResponseMessage Add(string message)
        {
            string currentUserName = this.RequestContext.Principal.Identity.Name;
            var operationResult = this.commentService.Add(currentUserName, message);
            if (operationResult.State.IsFail())
            {
                switch (operationResult.Code)
                {
                    case ErrorCode.ItemIsNotValid:
                        return this.Request.CreateResponse(HttpStatusCode.BadRequest);
                    case ErrorCode.Other:
                        return this.Request.CreateResponse(HttpStatusCode.InternalServerError);
                }
            }

            this.notificationHubContext.Clients.All.onNewComment(operationResult.Result);
            return this.Request.CreateResponse(HttpStatusCode.Created, operationResult.Result);
        }

        [HttpPost]
        [Route("{id}/{message}")]
        public HttpResponseMessage Update(Guid id, string message)
        {
            string currentUserName = this.RequestContext.Principal.Identity.Name;

            var operationResult = this.commentService.Update(currentUserName, id, message);
            if (operationResult.State.IsFail())
            {
                switch (operationResult.Code)
                {
                    case ErrorCode.ItemIsNotValid:
                        return this.Request.CreateResponse(HttpStatusCode.BadRequest);
                    case ErrorCode.NotFound:
                        return this.Request.CreateResponse(HttpStatusCode.NotFound);
                    case ErrorCode.Forbidden:
                        return this.Request.CreateResponse(HttpStatusCode.Forbidden);
                    case ErrorCode.Other:
                        return this.Request.CreateResponse(HttpStatusCode.InternalServerError);
                }
            }

            this.notificationHubContext.Clients.All.onUpdateComment(operationResult.Result);
            return this.Request.CreateResponse(HttpStatusCode.OK, operationResult.Result);
        }

        [HttpDelete]
        [Route("{id}")]
        public HttpResponseMessage Remove(Guid id)
        {
            string currentUserName = this.RequestContext.Principal.Identity.Name;

            var operationResult = this.commentService.Remove(currentUserName, id);
            if (operationResult.State.IsFail())
            {
                switch (operationResult.Code)
                {
                    case ErrorCode.ItemIsNotValid:
                        return this.Request.CreateResponse(HttpStatusCode.BadRequest);
                    case ErrorCode.NotFound:
                        return this.Request.CreateResponse(HttpStatusCode.NotFound);
                    case ErrorCode.Forbidden:
                        return this.Request.CreateResponse(HttpStatusCode.Forbidden);
                    case ErrorCode.Other:
                        return this.Request.CreateResponse(HttpStatusCode.InternalServerError);
                }
            }

            this.notificationHubContext.Clients.All.onRemoveComment(id);

            return this.Request.CreateResponse(HttpStatusCode.NoContent);
        }
    }
}

StudyProjects/Game_MVC_task14/Controllers/GameController.cs
using System;
using System.Web.Mvc;
using Game_MVC.Services.Interfaces;
using Game_MVC.Services.Interfaces.Projections;
using Game_MVC_task14.Hubs;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.SignalR;

namespace Game_MVC_task14.Controllers
{
    [RoutePrefix("game")]
    [System.Web.Mvc.Authorize]
    public class GameController : Controller
    {
        private readonly IGameService gameService;
        private readonly IHubContext gameHubContext;
        private readonly IUserService userService;

        public GameController(IGameService gameService, IUserService userService)
        {
            this.gameService = gameService;
            this.userService = userService;
            this.gameHubContext = GlobalHost.ConnectionManager.GetHubContext<GameHub>();
        }

        public ActionResult Index()
        {
            return this.View();
        }

        [Route("history")]
        public ActionResult GameHistory()
        {
            var result = this.gameService.GetGameHistory();
            if (result.State.IsFail())
            {
                return this.HttpNotFound();
            }

            return this.View(result.Result);
        }

        [Route("history/details/{id}")]
        public ActionResult GameDetails(Guid id)
        {
            var result = this.gameService.GetGameDetails(id);
            if (result.State.IsFail())
            {
                return this.HttpNotFound();
            }

            return this.View(result.Result);
        }

        [HttpPost]
        [Route("compare/{number}")]
        public ActionResult CompareNumber(int number)
        {
            UserProjection user = this.GetCurrentUser();

            var compareNumberResult = this.gameService.CompareNumber(user, number);

            if (compareNumberResult.State.IsFail())
            {
                return this.Json(new { result = "error", message = "Something went wrong" });
            }

            switch (compareNumberResult.Result)
            {
                case 1:
                    return this.Json(new { result = "loss", message = "Number is less" });
                case -1:
                    return this.Json(new { result = "loss", message = "Number is more" });
                case 0:
                    this.gameHubContext.Clients.All.onGameOver(user.Name, $"The user '{user.Name}' win. Number: {number}");
                    return this.Json(new { result = "win", message = "You win!!!" });
            }

            return this.Json(new { result = "error", message = "Something went wrong" });
        }

        [HttpPost]
        [Route("set/{number}")]
        public void SetNumber(int number)
        {
            UserProjection user = this.GetCurrentUser();

            if (this.gameService.SetNumber(user, number).State.IsSuccess())
            {
                this.gameHubContext.Clients.All.onStartGame();
            }
        }

        [HttpPost]
        [Route("connect")]
        public ActionResult Connect()
        {
            string userName = this.User.Identity.Name;

            if (this.gameService.IsRunning)
            {
                return this.Json(new { userName, gameStatus = "running" });
            }

            return this.Json(new { userName, gameStatus = "stopped" });
        }

        [HttpPost]
        [Route("markYourSelf")]
        public void MarkYourSelf()
        {
            string userName = this.User.Identity.Name;
            this.gameHubContext.Clients.All.onMarkedOtherUsers(userName);
        }

        [HttpPost]
        [Route("rollColl")]
        public void RollColl()
        {
            string userName = this.User.Identity.Name;
            this.gameHubContext.Clients.All.onRollColl(userName);
        }

        private UserProjection GetCurrentUser()
        {
            Guid userId = Guid.Parse(this.User.Identity.GetUserId());
            var searchOperationResult = this.userService.GetFirst(u => u.Id == userId);
            if (searchOperationResult.State.IsFail())
            {
                return null;
            }

            return searchOperationResult.Result;
        }
    }
}

StudyProjects/Game_MVC_task14/Views/Game/Comments.cshtml
<h4>Comments:</h4>

<div class="container">
    <div class="row" style="border: 1px solid #ccc">
        <div class="col-xm-12" style="overflow-y: auto; height:150px;">
            <ul id="commentsList" class="list-group"></ul>
        </div>
    </div>
    <div class="row">
        <input id="inputComment" class="form-control" type="text">
        <input id="btnSendComment" class="btn" type="button" style="padding-right:100px" value="Send">

    </div>
</div>

StudyProjects/Game_MVC_task14/Views/Game/GameDetails.cshtml
@model IEnumerable<Game_MVC.Services.Interfaces.Projections.UserGameSessionProjection>

<table class="table">
    <tr>
        <th>
            #
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateTime)
        </th>
    </tr>

    @{
        int index = 0, nextWinNumber, prevWinNumber, winNumber, winNumber2 = 0, winNumber3 = 0;
        if (Model.Any())
        {
            winNumber = Model.First().Game.Number;
            winNumber2 = winNumber;
            if (Model.Any(gs => gs.Number != winNumber))
            {
                var sortedNumbers = Model
                    .OrderBy(i => i.Number);

                var nextWinner = sortedNumbers
                    .FirstOrDefault(gs => gs.Number > winNumber);
                nextWinNumber = nextWinner?.Number ?? winNumber;
                prevWinNumber = sortedNumbers
                    .Aggregate((s, gs) => gs.Number < winNumber? gs:s).Number;

                if (prevWinNumber == winNumber)
                {
                    winNumber2 = nextWinNumber;
                }else if (nextWinNumber == winNumber)
                {
                    winNumber2 = prevWinNumber;
                }
                else
                {
                    int offsetBack = Math.Abs(winNumber - prevWinNumber);
                    int offsetNext = Math.Abs(nextWinNumber - winNumber);

                    if (offsetBack == offsetNext)
                    {
                        winNumber2 = prevWinNumber;
                        winNumber3 = nextWinNumber;
                    }
                    else
                    {
                        winNumber2 = offsetBack < offsetNext ? prevWinNumber : nextWinNumber;
                    }
                }
            }

        }
    }

    @foreach (var item in Model)
    {
        <tr 
            @if (item.Number == item.Game.Number)
            {
                @: style=background-color:#62d462
            }
            else if (item.User != null && item.User.Name == User.Identity.Name) {
                if(item.Number==winNumber2 || item.Number==winNumber3)
                {
                    @: style=background-color:#9fd8ff
                }
                else { 
                    @: style=background-color:azure
                }
            }
            else if(item.Number==winNumber2 || item.Number==winNumber3)
            {
                @: style=background-color:#f2ff9f
            }
        >
    <td>
        @(++index)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.User.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Number)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DateTime)
    </td>
</tr>
}

</table>

StudyProjects/Game_MVC_task14/Views/Game/GameFrame.cshtml
<div class="container">
    <div id="setNumberBlock" class="row" hidden>
        <div class="col-sm-4 col-xs-12">
            <input id="inputNewNumber" type="number" class="form-control" placeholder="0">
        </div>
        <div class="col-sm-4 col-xs-12">
            <input id="btnSetNumber" type="button" class="btn btn-success" value="Set new number" />
        </div>
    </div>
    <div id="compareBlock" class="row" hidden>
        <div class="col-sm-4 col-xs-12">
            <input id="inputNumber" type="number" class="form-control" placeholder="0">
        </div>
        <div class="col-sm-4 col-xs-12">
            <input id="btnCompereNumber" type="button" class="btn btn-success" value="Compare number" />
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <p id="msg"></p>
        </div>
    </div>
    <div id="usersBlock" class="row">
        <h4>Other users:</h4>
        <div class="col-xs-12">
            <ul id="usersList"></ul>
        </div>
    </div>
</div>

StudyProjects/Game_MVC_task14/Views/Game/GameHistory.cshtml
@model IEnumerable<Game_MVC.Services.Interfaces.Projections.GameProjection>

<table class="table">
    <tr>
        <th>
            #
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Owner)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Winner)
        </th>
        <th>

        </th>
    </tr>
    @{ int index = 0; }
    @foreach (var item in Model) {
        <tr
            @if (item.Winner != null && item.Winner.Name == User.Identity.Name)
            {
                @:style=background-color:#62d462
            }else if (item.GameSessions.Any(gameSession => gameSession.User.Name==User.Identity.Name))
            {
                @:style=background-color:azure
            }
        >
        <td>
            @(++index)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Owner.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Winner.Name)
        </td>
        <td>
            <a href="@Url.Action("GameDetails","Game",new{id=item.Id})">Details</a>
        </td>
    </tr>
    }

</table>

StudyProjects/Game_MVC_task14/Views/Game/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>User: @User.Identity.Name</h2>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            @Html.Partial("GameFrame")
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            @Html.Partial("Comments")
        </div>
    </div>
</div>

@section Scripts{
    <!--Ссылка на библиотеку SignalR -->
    <script src="~/Scripts/jquery.signalR-2.4.0.min.js"></script>
    <!--Ссылка на автоматически сгенерированный скрипт хаба SignalR -->
    <script src="~/signalr/hubs"></script>
    <script src="~/Scripts/gameHub.js"></script>
    <script src="~/Scripts/commentHub.js"></script>
}