StudHelper/StudHelper.Web/Controllers/GroupController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudHelper.Application.Interfaces.Services;
using StudHelper.Application.ViewModels.Group;
using StudHelper.Web.Utils;

namespace StudHelper.Web.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        private const int PageSize = 4;
        private const int MaxPage = 4;
        private readonly IGroupService groupService;

        public GroupController(IGroupService groupService)
        {
            this.groupService = groupService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Info(int id)
        {
           var model = await this.groupService.GetAsync(id);
            if (model == null)
            {
                return this.NotFound();
            }

            return this.View(model);
        }

        [AllowAnonymous]
        public async Task<IActionResult> List(int page = 1)
        {
            int offset = (page - 1) * PageSize;
            var groupListItems = await this.groupService.GetAllAsync(offset, PageSize);
            int totalSize = await this.groupService.CountAsync();
            var viewModel = new GroupListViewModel()
            {
                Groups = groupListItems,
                Pager = new JW.Pager(totalSize, page, PageSize, MaxPage)
            };

            return this.View(viewModel);
        }

        public IActionResult Create()
        {
            var viewModel = new CreateGroupViewModel();
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateGroupViewModel viewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(viewModel);
            }

            viewModel.OwnerId = this.User.GetUserId();
            var addResult = await this.groupService.AddAsync(viewModel);

            if (!addResult.IsSucceeded)
            {
                return this.StatusCode(500);
            }

            return this.RedirectToAction("Info", new { id=viewModel.Id });
        }

        public async Task<IActionResult> Update(int id)
        {
            int userId = this.User.GetUserId();
            var viewModelResult = await this.groupService.GetToUpdateAsync(userId, id);
            if (!viewModelResult.IsSucceeded)
            {
                return this.NotFound();
            }

            return this.View(viewModelResult.Result);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateGroupViewModel viewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(viewModel);
            }

            int userId = this.User.GetUserId();
            var addResult = await this.groupService.UpdateAsync(userId, viewModel);

            if (!addResult.IsSucceeded)
            {
                return this.StatusCode(500);
            }

            return this.RedirectToAction("Info", new { id = viewModel.Id });
        }
    }
}

StudHelper/StudHelper.Web/Controllers/UserController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StudHelper.Application.Interfaces.Services;

namespace StudHelper.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        public async Task<IActionResult> Profile(int id)
        {
            var model = await this.userService.GetUserAsync(u => u.Id == id);

            if (!model.IsSucceeded)
            {
                return this.StatusCode(500);
            }

            return this.View(model.Result);
        }
    }
}

StudHelper/StudHelper.Web/Views/Group/Create.cshtml
@using StudHelper.Application.ViewModels.Resource
@using StudHelper.Application.ViewModels.Group
@model CreateGroupViewModel

<div class="container mt-3">
    <div class="row">
        <div class="col-12">
            <p class="h2">Create a new group</p>
            <hr />
            <div id="content"></div>
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="OwnerId" hidden />
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-lg-4 form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mt-4">
                        <div class="col-12 form-group ml-auto mb-1">
                            <div class="d-flex w-100 justify-content-between">
                                <div class="h5 mt-auto">Resources</div>
                                <button type="button" class="btn btn-success" data-mode="add" onclick="groupViewModel.showResourceModal(this)">Add resource</button>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 form-group">
                            <input id="btn_save" type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="resourceTemplate" hidden>
    <div resources-item class="list-group-item list-group-item-action flex-column align-items-start">
        <span resource-title class="h5 mb-1 p-1">{title}</span>
        <input resource-title hidden value="{title}" />
        <p resource-description class="mb-1 p-1 w-100">{description}</p>
        <input resource-description hidden value="{description}" />
        <div class="row">
            <div class="mr-3 ml-auto btn-group " role="group">
                <button type="button" class="btn btn-secondary" data-mode="edit" onclick="groupViewModel.showResourceModal(this)">edit</button>
            </div><button type="button" class="btn btn-secondary" onclick="groupViewModel.onBtnResourceDeleteClick(this)">delete</button>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/js/create-group.js"></script>
    <partial name="_ValidationScriptsPartial" />
}

StudHelper/StudHelper.Web/Views/Group/Info.cshtml
@model StudHelper.Application.ViewModels.Group.GroupViewModel

@{
    ViewData["Title"] = "Info";
}

@section Styles{
    <link href="~/css/group-info.css" rel="stylesheet" />
}

<div class="container mt-3">
    <div class="row">
        <div class="col-12">
            <div class="container mt-4">
                <div class="row">
                    <div class="col-12 form-group">
                        <h2 class="control-label">@Model.Title</h2>
                        <hr />
                        <span class="owner_user-name_opacity">Owner: <a asp-controller="User" asp-action="Profile" asp-route-id="@(Model.Owner.Id)">@Model.Owner.UserName</a></span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12 form-group">
                        <p class="control-label group__description">@Model.Description</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 ml-auto mb-1">
                        <div class="mt-auto">
                            <h5>Resources</h5>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 form-group">
                        <div id="resource_list" class="list-group">

                            @foreach (var resource in Model.Resources)
                            {
                                <div resources-item class="list-group-item list-group-item-action flex-column align-items-start">
                                    <h5>
                                        <span resource-title>@resource.Title</span>
                                    </h5>
                                    <p class="mb-1 p-1 w-100">@resource.Description</p>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

StudHelper/StudHelper.Web/Views/Group/List.cshtml
@model StudHelper.Application.ViewModels.Group.GroupListViewModel

@section Styles{ 
    <link href="~/css/list.css" rel="stylesheet"/>
}

<div class="container mt-3 groups">
    <div class="row">
        <div class="col-12">
            <div class="groups__header align-items-end mb-3">
                <span class="display-4">Groups </span>
                <a asp-action="Create" asp-controller="Group" class="btn btn-success">
                    <h5 class="groups__create_indent h-light "><i class="fas fa-plus-circle"></i> New group</h5>
                </a>
            </div>
            <table class="table">
                <tbody>
                    @foreach (var group in Model.Groups)
                    {
                        <tr>
                            <td>
                                <div class="d-flex flex-column">
                                    <a asp-action="Info" asp-route-id="@(group.Id)">
                                        <h2>@group.Title</h2>
                                    </a>
                                    <span class="owner_user-name_opacity">Owner: <a asp-controller="User" asp-action="Profile" asp-route-id="@(group.OwnerId)">@group.OwnerName</a></span>
                                    <br />
                                    <p>@group.Description</p>
                                </div>
                            </td>
                        </tr>
                    }
                    <tr>
                        <td>
                            <page-links pager="@Model.Pager" page-action="List" class="groups__paging_align"></page-links>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

StudHelper/StudHelper.Web/Views/Group/Update.cshtml
@using StudHelper.Application.ViewModels.Resource
@using StudHelper.Application.ViewModels.Group
@model UpdateGroupViewModel

<div class="container mt-3">
    <div class="row">
        <div class="col-12">
            <p class="h2">Update group</p>
            <hr />
            <div id="content"></div>
            <form asp-action="Update">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-lg-4 form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 form-group">
                            <label asp-for="Description" class="control-label"></label>
                            <textarea asp-for="Description" rows="5" class="form-control"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="row mt-4">
                        <div class="col-12 form-group ml-auto mb-1">
                            <div class="d-flex w-100 justify-content-between">
                                <div class="h5 mt-auto">Resources</div>
                                <button type="button" class="btn btn-success" data-mode="add" onclick="groupViewModel.showResourceModal(this)">Add resource</button>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 form-group">
                            <div id="resource_list" class="list-group"
                                 data-resource-title-name-template="Resources[{index}].Title"
                                 data-resource-description-name-template="Resources[{index}].Description">

                                @for (int i = 0; i < Model.Resources?.Count; i++)
                                {
                                <div resources-item class="list-group-item list-group-item-action flex-column align-items-start">
                                    <span resource-title class="h5 mb-1 p-1">@Model.Resources[i].Title</span>
                                    <input resource-title asp-for="Resources[i].Title" hidden />

                                    <p resource-description name="Resources[@(i)].Description" class="mb-1 p-1 w-100">@Model.Resources[i].Description</p>
                                    <input resource-description asp-for="Resources[i].Description" hidden />

                                    <div class="row">
                                        <div class="mr-3 ml-auto btn-group " role="group">
                                            <button type="button" class="btn btn-secondary" data-mode="edit" onclick="groupViewModel.showResourceModal(this)">edit</button>
                                            <button type="button" class="btn btn-secondary" onclick="groupViewModel.onBtnResourceDeleteClick(this)">delete</button>
                                        </div>
                                    </div>
                                </div>
                                }
                            </div>

                            <span id="resourceErrorMsg" asp-validation-for="Resources"></span>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-12 form-group">
                            <input id="btn_save" type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="resourceTemplate" hidden>
    <div resources-item class="list-group-item list-group-item-action flex-column align-items-start">
        <span resource-title class="h5 mb-1 p-1">{title}</span>
        <input resource-title hidden value="{title}" />
        <p resource-description class="mb-1 p-1 w-100">{description}</p>
        <input resource-description hidden value="{description}" />
        <div class="row">
            <div class="mr-3 ml-auto btn-group " role="group">
                <button type="button" class="btn btn-secondary" data-mode="edit" onclick="groupViewModel.showResourceModal(this)">edit</button>
            </div><button type="button" class="btn btn-secondary" onclick="groupViewModel.onBtnResourceDeleteClick(this)">delete</button>
        </div>
    </div>
</div>

<partial name="_UpdateResource" model="@(new ResourceViewModel())" />

@section Scripts{
    <script src="~/js/create-group.js"></script>
    <partial name="_ValidationScriptsPartial" />
}

StudHelper/StudHelper.Web/Views/Group/_UpdateResource.cshtml
@model StudHelper.Application.ViewModels.Resource.ResourceViewModel

<div class="modal fade" modal="resource" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form>
                <div class="modal-header">
                    <h5 class="modal-title">New resource</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="col-form-label">Title:</label>
                        <input asp-for="Title" resource-title class="form-control" />
                        <span asp-validation-for="Title"></span>
                    </div>
                    <div class="form-group">
                        <label class="col-form-label">Description:</label>
                        <textarea asp-for="Description" resource-description class="form-control"></textarea>
                        <span asp-validation-for="Description"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal" action-cancel>Close</button>
                    <button type="button" class="btn btn-primary" action-apply>Apply</button>
                </div>
            </form>
        </div>
    </div>
</div>