StudHelper/StudHelper.Web/Controllers/SettingsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudHelper.Application.Interfaces.Services;
using StudHelper.Application.ViewModels.Settings;
using StudHelper.Web.Utils;

namespace StudHelper.Web.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        private readonly IUserService userService;

        public SettingsController(IUserService userService)
        {
            this.userService = userService;
        }

        public async Task<IActionResult> Profile()
        {
            int userId = this.User.GetUserId();

            var resultViewModel = await this.userService.GetUserAsync(u => u.Id == userId);

            if (!resultViewModel.IsSucceeded)
            {
                return this.StatusCode(500);
            }

            var model = new SettingProfileViewModel(resultViewModel.Result);
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Profile(SettingProfileViewModel model)
        {
            model.Done = false;

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            model.UserId = this.User.GetUserId();
            var result = await this.userService.UpdateAsync(this.User.GetUserId(), model);

            if (!result.IsSucceeded)
            {
                foreach (var error in result.Errors)
                {
                    this.ModelState.AddModelError(string.Empty, error);
                }
            }
            else
            {
                model.Done = true;
            }

            return this.View(model);
        }

        public async Task<IActionResult> Password()
        {
            int userId = this.User.GetUserId();
            var resultViewModel = await this.userService.GetUserAsync(u => u.Id == userId);

            if (!resultViewModel.IsSucceeded)
            {
                return this.StatusCode(500);
            }

            var model = new SettingPasswordViewModel(resultViewModel.Result);
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Password(SettingPasswordViewModel model)
        {
            model.Done = false;

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            model.UserId = this.User.GetUserId();

            var result = await this.userService.ChangePasswordAsync(model);

            if (!result.IsSucceeded)
            {
                foreach (var error in result.Errors)
                {
                    this.ModelState.AddModelError(string.Empty, error);
                }
            }
            else
            {
                model.Done = true;
            }

            return this.View(model);
        }
    }
}

StudHelper/StudHelper.Web/Controllers/UserController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StudHelper.Application.Interfaces.Services;

namespace StudHelper.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        public async Task<IActionResult> Profile(int id)
        {
            var model = await this.userService.GetUserAsync(u => u.Id == id);

            if (!model.IsSucceeded)
            {
                return this.StatusCode(500);
            }

            return this.View(model.Result);
        }
    }
}

StudHelper/StudHelper.Web/Views/User/Profile.cshtml
@using StudHelper.Web.Utils;
@model StudHelper.Application.ViewModels.User.UserViewModel

@{
    ViewData["Title"] = "Profile";
    int userId = this.User.GetUserId();
}

@section Styles {
    <link href="~/css/user.css" rel="stylesheet" />
}

<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-12">
            <div class="card-title md-4">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <div class="d-block d-md-none">
                                <div class="d-flex flex-column justify-content-sm-start">
                                    <div class="d-block">
                                        <div class="row justify-content-between">
                                            <div class="col-auto">
                                                <h2>
                                                    @Html.DisplayFor(model => model.LastName) @Html.DisplayFor(model => model.FirstName)
                                                </h2>
                                            </div>
                                            @if (userId == Model.Id)
                                            {
                                                <div class="ml-auto">
                                                    <h2>
                                                        <a class="btn btn-primary" role="button" id="btnDiscard" asp-action="Profile" asp-controller="Settings">Edit</a>
                                                    </h2>
                                                </div>
                                            }
                                        </div>
                                    </div>
                                    <div class="image-container" style="width: 150px; height: 150px">
                                        <img src="http://placehold.it/150x150" id="imgProfile" class="img-thumbnail">
                                        @if (userId == Model.Id)
                                        {
                                            <div class="middle">
                                                <input type="button" class="btn btn-secondary" id="btnChangePicture" value="Change">
                                                <input type="file" style="display: none;" id="profilePicture" name="file">
                                            </div>
                                        }
                                    </div>

                                    <div class="user-data mt-3">
                                        <div class="d-block">
                                            <h6>
                                                <span class="user-data-item">
                                                    @Html.DisplayNameFor(model => model.UserName):
                                                </span>
                                                @Html.DisplayFor(model => model.UserName)
                                            </h6>
                                        </div>
                                        <div class="d-block">
                                            <h6>
                                                <span class="user-data-item">
                                                    @Html.DisplayNameFor(model => model.Email):
                                                </span>
                                                @Html.DisplayFor(model => model.Email)
                                            </h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="d-none d-md-block">
                                <div class="d-flex flex-row justify-content-sm-start">
                                    <div class="image-container">
                                        <img src="http://placehold.it/150x150" id="imgProfile" style="width: 150px; height: 150px" class="img-thumbnail">
                                        @if (userId == Model.Id)
                                        {
                                            <div class="middle">
                                                <input type="button" class="btn btn-secondary" id="btnChangePicture" value="Change">
                                                <input type="file" style="display: none;" id="profilePicture" name="file">
                                            </div>
                                        }
                                    </div>

                                    <div class="user-data ml-3">
                                        <h2 class="d-block">
                                            @Html.DisplayFor(model => model.LastName) @Html.DisplayFor(model => model.FirstName)
                                        </h2>
                                        <div class="d-block">
                                            <h6>
                                                <span class="user-data-item">
                                                    @Html.DisplayNameFor(model => model.UserName):
                                                </span>
                                                @Html.DisplayFor(model => model.UserName)
                                            </h6>
                                        </div>
                                        <div class="d-block">
                                            <h6>
                                                <span class="user-data-item">
                                                    @Html.DisplayNameFor(model => model.Email):
                                                </span>
                                                @Html.DisplayFor(model => model.Email)
                                            </h6>
                                        </div>
                                    </div>

                                    @if (userId == Model.Id)
                                    {
                                        <div class="ml-auto">
                                            <a class="btn btn-primary" role="button" id="btnDiscard" asp-action="Profile" asp-controller="Settings">Edit</a>
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>