StudyProjects/Education_MVC_Routing/ViewModels/CategoryViewModel.cs
namespace Education_MVC_Routing.ViewModels
{
    public class CategoryViewModel
    {
        public string CategoryName { get; set; }

        public string SubCategoryName { get; set; }

        public CategoryViewModel() { }

        public CategoryViewModel(string categoryName):this(categoryName,null)
        {

        }

        public CategoryViewModel(string categoryName, string subCategoryName)
        {
            this.CategoryName = categoryName;
            this.SubCategoryName = subCategoryName;
        }
    }
}

StudyProjects/Education_MVC_Routing/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Education_MVC_Routing.Controllers
{
    public class AccountController : Controller
    {
        public ActionResult LogOn()
        {
            return View();
        }

        public ActionResult LogOff()
        {
            return View();
        }
    }
}

StudyProjects/Education_MVC_Routing/Controllers/CategoriesController.cs
using System.Web.Mvc;
using Education_MVC_Routing.ViewModels;

namespace Education_MVC_Routing.Controllers
{
    public class CategoriesController : Controller
    {
        public ActionResult List()
        {
            return View();
        }

        public ActionResult Category(string categoryName)
        {
            return View(new CategoryViewModel(categoryName));
        }

        public ActionResult SubCategories(string categoryName)
        {
            return View(new CategoryViewModel(categoryName));
        }

        public ActionResult SubCategory(string categoryName, string subCategoryName)
        {
            return View(new CategoryViewModel(categoryName, subCategoryName));
        }
    }
}

StudyProjects/Education_MVC_Routing/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Education_MVC_Routing.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

StudyProjects/Education_MVC_Routing/Views/Categories/Category.cshtml
@using Education_MVC_Routing.ViewModels;
@model CategoryViewModel

@{
    ViewBag.Title = "Category";
}

<h2>Category</h2>
<div>@Model.CategoryName</div>

StudyProjects/Education_MVC_Routing/Views/Categories/List.cshtml
@{
    ViewBag.Title = "List";
}

<h2>List</h2>

StudyProjects/Education_MVC_Routing/Views/Categories/SubCategories.cshtml
@using Education_MVC_Routing.ViewModels;
@model CategoryViewModel

@{
    ViewBag.Title = "SubCategories";
}

<h2>SubCategories</h2>
<div>@Model.CategoryName</div>
<div>@Model.SubCategoryName</div>

StudyProjects/Education_MVC_Routing/Views/Categories/SubCategory.cshtml
@using Education_MVC_Routing.ViewModels;
@model CategoryViewModel

@{
    ViewBag.Title = "SubCategory";
}

<h2>SubCategory</h2>
<div>@Model.CategoryName</div>
<div>@Model.SubCategoryName</div>

StudyProjects/Education_MVC_Routing/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Маршруты</h2>

<ul style="list-style-type:none">
    <li>(пустой маршрут) - @Url.Action("Index", "Home")</li>
    <li>categories - @Url.Action("List", "Categories")</li>
    <li>category/{categoryName} - @Url.Action("Category", "Categories", new { categoryName = "SomeCategory" })</li>
    <li>category/{categoryName}/subcategories - @Url.Action("SubCategories", "Categories", new { categoryName = "SomeCategory" })</li>
    <li>category/{categoryName}/{subCategoryName} - @Url.Action("SubCategory", "Categories", new { categoryName = "SomeCategory", subCategoryName = "SomeSubCategory" })</li>
    <li>logon - @Url.Action("LogOn", "Account")</li>
    <li>logoff - @Url.Action("LogOff", "Account")</li>
    <li></li>
</ul>

StudyProjects/Education_MVC_Routing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
</head>

<body>
    @RenderBody()
</body>
</html>